export type SectionKey = "general" | "obituary" | "deathCertificate" | "embalming";
type Field = { name: string; label: string; type?: "text" | "date" | "time" | "email" | "tel" | "number" | "textarea" | "select"; options?: string[]; required?: boolean };
type Group = { title: string; fields: Field[] };
export const fields: Record<SectionKey, Group[]> = {
  general: [
    { title: "Decedent information", fields: [
      { name: "fullName", label: "Full name", required: true }, { name: "usualResidence", label: "Usual residence" }, { name: "state", label: "State" }, { name: "county", label: "County" }, { name: "city", label: "City" }, { name: "placeOfDeath", label: "Place of death" }, { name: "hospitalOrResidence", label: "Hospital or residence" }, { name: "otherPlace", label: "Other" }, { name: "dateOfDeath", label: "Date of death", type: "date" }, { name: "timeOfDeath", label: "Time", type: "time" }, { name: "dateOfBirth", label: "Date of birth", type: "date" }, { name: "age", label: "Age", type: "number" }, { name: "placeOfBirth", label: "Place of birth" }, { name: "maritalStatus", label: "Marital status", type: "select", options: ["Married", "Single", "Widowed", "Divorced"] }, { name: "education", label: "Educational background - highest grade completed" }, { name: "spouse", label: "Husband or wife (maiden name)" }, { name: "father", label: "Father's name" }, { name: "mother", label: "Mother's name" }, { name: "occupation", label: "Deceased occupation" }, { name: "business", label: "Kind of business" }, { name: "veteran", label: "Veteran", type: "select", options: ["Yes", "No"] }, { name: "decorations", label: "Any decorations" },
    ]},
    { title: "Informant and insurance", fields: [{ name: "informantName", label: "Informant name" }, { name: "informantAddress", label: "Address" }, { name: "informantTelephone", label: "Telephone", type: "tel" }, { name: "insuranceInformation", label: "Insurance information", type: "textarea" }, { name: "policyNumber", label: "Policy number" }] },
    { title: "Service information", fields: [{ name: "funeralDate", label: "Date of funeral", type: "date" }, { name: "funeralTime", label: "Time", type: "time" }, { name: "funeralPlace", label: "Place of funeral service" }, { name: "officiant", label: "Pastor or minister officiating" }, { name: "ministerNotified", label: "Has pastor or minister been notified?", type: "select", options: ["Yes", "No"] }, { name: "cemeteryName", label: "Cemetery name" }, { name: "cemeteryLocation", label: "Location" }] },
  ],
  obituary: [
    { title: "Personal information", fields: [{ name: "name", label: "Name", required: true }, { name: "age", label: "Age", type: "number" }, { name: "address", label: "Address" }, { name: "city", label: "City" }, { name: "state", label: "State" }, { name: "zip", label: "ZIP code" }, { name: "dateOfDeath", label: "Date of death", type: "date" }, { name: "placeOfDeath", label: "Place of death" }] },
    { title: "Viewing and service information", fields: [{ name: "viewingDate", label: "Viewing date", type: "date" }, { name: "viewingTime", label: "Viewing time", type: "time" }, { name: "viewingPlace", label: "Viewing place" }, { name: "wakeDate", label: "Wake service date", type: "date" }, { name: "wakeTime", label: "Wake time", type: "time" }, { name: "wakePlace", label: "Wake place" }, { name: "viewingAtChurch", label: "Viewing at church" }, { name: "serviceDate", label: "Funeral service date", type: "date" }, { name: "serviceTime", label: "Service time", type: "time" }, { name: "servicePlace", label: "Place of funeral service" }, { name: "cemetery", label: "Cemetery" }] },
    { title: "Life and family information", fields: [{ name: "dateOfBirth", label: "Date of birth", type: "date" }, { name: "placeOfBirth", label: "Place of birth" }, { name: "parents", label: "Name of parents" }, { name: "organizations", label: "Organizations and clubs", type: "textarea" }, { name: "lifeDetails", label: "Life details to include", type: "textarea" }, { name: "precededInDeath", label: "Preceded in death by", type: "textarea" }, { name: "survivors", label: "Survivors", type: "textarea" }, { name: "contactName", label: "Contact person name" }, { name: "contactPhone", label: "Phone", type: "tel" }, { name: "photo", label: "Optional photo (JPG, PNG, or WebP; 5 MB maximum)" }, { name: "familyApproval", label: "Final family approval", type: "select", options: ["Not ready for approval", "I approve this obituary information for staff review"] }] },
  ],
  deathCertificate: [
    { title: "Decedent information", fields: [{ name: "fullName", label: "Full name", required: true }, { name: "age", label: "Age", type: "number" }, { name: "dateOfBirth", label: "Date of birth", type: "date" }, { name: "streetAddress", label: "Street address" }, { name: "city", label: "City" }, { name: "county", label: "County" }, { name: "state", label: "State" }, { name: "zip", label: "ZIP code" }, { name: "placeOfBirth", label: "Place of birth" }, { name: "withinCityLimits", label: "Within city limits?", type: "select", options: ["Yes", "No"] }, { name: "veteran", label: "Veteran?", type: "select", options: ["Yes", "No"] }] },
    { title: "Family and marital information", fields: [{ name: "fatherName", label: "Father's name" }, { name: "motherFirst", label: "Mother's first name" }, { name: "motherMiddle", label: "Mother's middle name" }, { name: "motherMaiden", label: "Mother's maiden name (name she was born with)" }, { name: "maritalStatus", label: "Marital status", type: "select", options: ["Married", "Married, but separated", "Widowed", "Divorced", "Never Married"] }, { name: "survivingSpouse", label: "Surviving spouse" }, { name: "spouseMaiden", label: "Maiden name" }] },
    { title: "Education and employment", fields: [{ name: "education", label: "Highest level of education", type: "select", options: ["8th Grade or Less", "9th-12th, no diploma", "High School or GED", "Some College, No Degree", "Associate Degree", "Bachelor's Degree", "Master's Degree", "Doctorate Degree", "Unknown"] }, { name: "occupation", label: "Occupation (longest job held)" }, { name: "industry", label: "Industry" }] },
    { title: "Informant contact information", fields: [{ name: "informantName", label: "Informant's full name" }, { name: "relationship", label: "Relationship to decedent" }, { name: "mailingAddress", label: "Mailing address" }, { name: "email", label: "Email address", type: "email" }] },
    { title: "Death certificate order", fields: [{ name: "quantity", label: "Number of death certificates needed", type: "number", required: true }] },
  ],
  embalming: [
    { title: "Decedent", fields: [{ name: "decedentName", label: "Name of decedent", required: true }] },
    { title: "Authorization", fields: [{ name: "permission", label: "Permission to embalm", type: "select", options: ["YES - Permission Granted", "NO - Permission Refused"], required: true }] },
    { title: "Authorized representative", fields: [{ name: "representativeName", label: "Printed name of authorized representative", required: true }, { name: "relationship", label: "Relationship to decedent", required: true }, { name: "date", label: "Date", type: "date", required: true }, { name: "attestation", label: "Attestation", type: "select", options: ["I confirm and attest to the statements above"], required: true }, { name: "signatureIntent", label: "Intent to sign", type: "select", options: ["I intend for this electronic signature to authorize this form"], required: true }] },
  ],
};
export const labels: Record<SectionKey, string> = { general: "General Information", obituary: "Obituary", deathCertificate: "Mississippi Death Certificate Worksheet", embalming: "Permission to Embalm" };


