import { savePacketSectionAction } from "@/app/actions/family-care";
import type { FamilyCase, SectionKey } from "@/lib/family-care-types";
import { SignaturePad } from "@/components/signature-pad";

type Field = { name: string; label: string; type?: "text" | "date" | "time" | "email" | "tel" | "number" | "textarea" | "select"; options?: string[]; required?: boolean };
type Group = { title: string; fields: Field[] };
const fields: Record<SectionKey, Group[]> = {
  general: [
    { title: "Decedent information", fields: [
      { name: "fullName", label: "Full name", required: true }, { name: "usualResidence", label: "Usual residence" }, { name: "state", label: "State" }, { name: "county", label: "County" }, { name: "city", label: "City" }, { name: "placeOfDeath", label: "Place of death" }, { name: "hospitalOrResidence", label: "Hospital or residence" }, { name: "otherPlace", label: "Other" }, { name: "dateOfDeath", label: "Date of death", type: "date" }, { name: "timeOfDeath", label: "Time", type: "time" }, { name: "dateOfBirth", label: "Date of birth", type: "date" }, { name: "age", label: "Age", type: "number" }, { name: "placeOfBirth", label: "Place of birth" }, { name: "maritalStatus", label: "Marital status", type: "select", options: ["Married", "Single", "Widowed", "Divorced"] }, { name: "education", label: "Educational background - highest grade completed" }, { name: "spouse", label: "Husband or wife (maiden name)" }, { name: "father", label: "Father's name" }, { name: "mother", label: "Mother's name" }, { name: "occupation", label: "Deceased occupation" }, { name: "business", label: "Kind of business" }, { name: "veteran", label: "Veteran", type: "select", options: ["Yes", "No"] }, { name: "decorations", label: "Any decorations" },
    ]},
    { title: "Informant and insurance", fields: [{ name: "informantName", label: "Informant name" }, { name: "informantAddress", label: "Address" }, { name: "informantTelephone", label: "Telephone", type: "tel" }, { name: "insuranceInformation", label: "Insurance information", type: "textarea" }, { name: "policyNumber", label: "Policy number" }] },
    { title: "Service information", fields: [{ name: "funeralDate", label: "Date of funeral", type: "date" }, { name: "funeralTime", label: "Time", type: "time" }, { name: "funeralPlace", label: "Place of funeral service" }, { name: "officiant", label: "Pastor or minister officiating" }, { name: "ministerNotified", label: "Has pastor or minister been notified?", type: "select", options: ["Yes", "No"] }, { name: "cemeteryName", label: "Cemetery name" }, { name: "cemeteryLocation", label: "Location" }] },
  ],
  obituary: [
    { title: "Personal information", fields: [{ name: "name", label: "Name", required: true }, { name: "age", label: "Age", type: "number" }, { name: "address", label: "Address" }, { name: "city", label: "City" }, { name: "state", label: "State" }, { name: "zip", label: "ZIP code" }, { name: "dateOfDeath", label: "Date of death", type: "date" }, { name: "placeOfDeath", label: "Place of death" }] },
    { title: "Viewing and service information", fields: [{ name: "viewingDate", label: "Viewing date", type: "date" }, { name: "viewingTime", label: "Viewing time", type: "time" }, { name: "viewingPlace", label: "Viewing place" }, { name: "wakeDate", label: "Wake service date", type: "date" }, { name: "wakeTime", label: "Wake time", type: "time" }, { name: "wakePlace", label: "Wake place" }, { name: "viewingAtChurch", label: "Viewing at church" }, { name: "serviceDate", label: "Funeral service date", type: "date" }, { name: "serviceTime", label: "Service time", type: "time" }, { name: "servicePlace", label: "Place of funeral service" }, { name: "cemetery", label: "Cemetery" }] },
    { title: "Life and family information", fields: [{ name: "dateOfBirth", label: "Date of birth", type: "date" }, { name: "placeOfBirth", label: "Place of birth" }, { name: "parents", label: "Name of parents" }, { name: "organizations", label: "Organizations and clubs", type: "textarea" }, { name: "lifeDetails", label: "Life details to include", type: "textarea" }, { name: "precededInDeath", label: "Preceded in death by", type: "textarea" }, { name: "survivors", label: "Survivors", type: "textarea" }, { name: "contactName", label: "Contact person name" }, { name: "contactPhone", label: "Phone", type: "tel" }, { name: "photo", label: "Optional photo (JPG, PNG, or WebP; 5 MB maximum)" }, { name: "familyApproval", label: "Final family approval", type: "select", options: ["Not ready for approval", "I approve this obituary information for staff review"] }] },
  ],
  deathCertificate: [
    { title: "Decedent information", fields: [{ name: "fullName", label: "Full name", required: true }, { name: "age", label: "Age", type: "number" }, { name: "dateOfBirth", label: "Date of birth", type: "date" }, { name: "streetAddress", label: "Street address" }, { name: "city", label: "City" }, { name: "county", label: "County" }, { name: "state", label: "State" }, { name: "zip", label: "ZIP code" }, { name: "placeOfBirth", label: "Place of birth" }, { name: "withinCityLimits", label: "Within city limits?", type: "select", options: ["Yes", "No"] }, { name: "veteran", label: "Veteran?", type: "select", options: ["Yes", "No"] }] },
    { title: "Family and marital information", fields: [{ name: "fatherName", label: "Father's name" }, { name: "motherFirst", label: "Mother's first name" }, { name: "motherMiddle", label: "Mother's middle name" }, { name: "motherMaiden", label: "Mother's maiden name (name she was born with)" }, { name: "maritalStatus", label: "Marital status", type: "select", options: ["Married", "Married, but separated", "Widowed", "Divorced", "Never Married"] }, { name: "survivingSpouse", label: "Surviving spouse" }, { name: "spouseMaiden", label: "Maiden name" }] },
    { title: "Education and employment", fields: [{ name: "education", label: "Highest level of education", type: "select", options: ["8th Grade or Less", "9th-12th, no diploma", "High School or GED", "Some College, No Degree", "Associate Degree", "Bachelor's Degree", "Master's Degree", "Doctorate Degree", "Unknown"] }, { name: "occupation", label: "Occupation (longest job held)" }, { name: "industry", label: "Industry" }] },
    { title: "Informant contact information", fields: [{ name: "informantName", label: "Informant's full name" }, { name: "relationship", label: "Relationship to decedent" }, { name: "mailingAddress", label: "Mailing address" }, { name: "email", label: "Email address", type: "email" }] },
    { title: "Death certificate order", fields: [{ name: "quantity", label: "Number of death certificates needed", type: "number", required: true }] },
  ],
  embalming: [
    { title: "Decedent", fields: [{ name: "decedentName", label: "Name of decedent", required: true }] },
    { title: "Authorization", fields: [{ name: "permission", label: "Permission to embalm", type: "select", options: ["YES - Permission Granted", "NO - Permission Refused"], required: true }] },
    { title: "Authorized representative", fields: [{ name: "representativeName", label: "Printed name of authorized representative", required: true }, { name: "relationship", label: "Relationship to decedent", required: true }, { name: "date", label: "Date", type: "date", required: true }, { name: "attestation", label: "Attestation", type: "select", options: ["I confirm and attest to the statements above"], required: true }, { name: "signatureIntent", label: "Intent to sign", type: "select", options: ["I intend for this electronic signature to authorize this form"], required: true }] },
  ],
};
const labels: Record<SectionKey, string> = { general: "General Information", obituary: "Obituary", deathCertificate: "Mississippi Death Certificate Worksheet", embalming: "Permission to Embalm" };
function FieldInput({ field, value }: { field: Field; value?: string }) {
  const common = { name: field.name, defaultValue: value, required: field.required, className: "mt-2 w-full rounded-xl border border-stone-300 bg-white px-4 py-3 text-slate-950 outline-none focus:border-[#7b1e32] focus:ring-2 focus:ring-[#c6a15b]/40" };
  if (field.name === "photo") return <input type="file" name="photo" accept="image/jpeg,image/png,image/webp" className={common.className} />;
  if (field.type === "textarea") return <textarea {...common} rows={4} />;
  if (field.type === "select") return <select {...common}><option value="">Select</option>{field.options?.map((option) => <option key={option}>{option}</option>)}</select>;
  return <input {...common} type={field.type || "text"} />;
}
export function FamilyPacket({ item, token, active, typedSignatureEnabled }: { item: FamilyCase; token: string; active: SectionKey; typedSignatureEnabled: boolean }) {
  const section = item.sections[active];
  return <main className="min-h-screen bg-[#faf7f1] text-slate-900"><header className="border-b-4 border-[#c6a15b] bg-[#6e172c] px-5 py-6 text-white shadow-sm"><div className="mx-auto flex max-w-4xl items-center justify-between gap-5"><div>{item.isDemo && <p className="mb-3 inline-block rounded-full bg-[#f5e6bb] px-3 py-1 text-xs font-bold text-[#561324]">DEMO · FICTIONAL SAMPLE · NO EMAIL SENT</p>}<p className="text-xs font-semibold uppercase tracking-[.28em] text-[#f2d486]">Marshall Funeral Home</p><h1 className="mt-2 text-3xl font-semibold">Family Care Packet</h1><p className="mt-2 text-sm text-[#fdf6e7]">Private case for {item.decedentName} · Link expires {new Date(item.access.expiresAt).toLocaleDateString()}</p></div><span aria-label="Marshall Funeral Home M mark" className="grid size-20 shrink-0 place-items-center rounded-full border-2 border-[#f2d486] font-serif text-6xl font-bold leading-none text-[#f2d486] drop-shadow-md sm:size-24 sm:text-7xl">M</span></div></header>
    <div className="mx-auto max-w-4xl px-4 py-6"><nav aria-label="Packet sections" className="grid grid-cols-2 gap-2 md:grid-cols-4">{(Object.keys(labels) as SectionKey[]).map((key) => <a href={`/family/${token}?section=${key}`} key={key} className={`rounded-xl border px-3 py-3 text-center text-xs font-semibold transition-colors ${key === active ? "border-[#6e172c] bg-[#6e172c] text-white" : "border-[#dccda8] bg-white text-black hover:border-[#c6a15b]"}`}>{labels[key]}<span className={`mt-1 block font-normal capitalize ${key === active ? "text-white" : "text-black"}`}>{item.sections[key].status.replace("-", " ")}</span></a>)}</nav>
      <section className="mt-6 rounded-3xl border border-[#e4d7b7] bg-white p-5 shadow-sm md:p-8"><p className="text-xs font-semibold uppercase tracking-[.24em] text-[#7b1e32]">Section</p><h2 className="mt-2 text-3xl font-semibold text-[#3f1420]">{labels[active]}</h2><p className="mt-2 text-sm text-slate-600">Save anytime and return with this same private link. Submit when this section is ready for Marshall staff review.</p>
        {active === "deathCertificate" && <div className="mt-5 rounded-2xl bg-amber-50 p-4 text-sm leading-6"><strong>First Copy: $17.00 · Additional Copies: $8.00 each</strong><br />INSURANCE NOTICE: If you have insurance for us to process, we will send one to the company for you, so you may want to order one additional copy.</div>}
        {active === "obituary" && item.photo && <div className="mt-5 flex items-center gap-4 rounded-2xl border border-[#7b1e32]/20 bg-[#fbf4e4] p-4"><div aria-hidden="true" className="grid size-16 shrink-0 place-items-center rounded-full bg-[#6e172c] text-xl font-bold text-[#f2d486]">ER</div><div><p className="text-sm font-semibold">DEMO obituary photo attached</p><p className="mt-1 text-xs text-slate-600">{item.photo.originalName} · fictional portrait placeholder · stored privately</p></div></div>}
        {active === "embalming" && <div className="mt-5 space-y-3 rounded-2xl border-2 border-amber-700/30 bg-amber-50 p-4 text-sm leading-6"><p>I confirm that I am authorized to make this decision for the decedent named above.</p><p>My signature below records the permission selected above as an electronic authorization pending staff review.</p><p className="font-semibold">I understand that if cremation is selected, all arrangements, authorizations, and payment must be completed within 48 hours. If not, embalming will be required.</p><p className="text-amber-900">Marshall staff will review this electronic authorization. This form does not verify identity and is not presented as a legal guarantee.</p></div>}
        <form action={savePacketSectionAction} encType="multipart/form-data" className="mt-7 space-y-8"><input type="hidden" name="token" value={token} /><input type="hidden" name="section" value={active} />{fields[active].map((group) => <fieldset key={group.title}><legend className="text-lg font-semibold text-[#6e172c]">{group.title}</legend><div className="mt-4 grid gap-4 md:grid-cols-2">{group.fields.map((field) => <label key={field.name} className={`text-sm font-medium text-slate-700 ${field.type === "textarea" ? "md:col-span-2" : ""}`}>{field.label}{field.required && " *"}<FieldInput field={field} value={section.data[field.name]} /></label>)}</div></fieldset>)}{active === "embalming" && <fieldset><legend className="text-lg font-semibold text-[#6e172c]">Electronic signature *</legend><SignaturePad /></fieldset>}<div className="sticky bottom-3 flex gap-3 rounded-2xl border border-[#e4d7b7] bg-white/95 p-3 shadow-lg backdrop-blur"><button name="intent" value="save" className="flex-1 rounded-full border border-[#7b1e32] px-4 py-3 font-semibold text-[#6e172c]">Save & return later</button><button name="intent" value="submit" className="flex-1 rounded-full bg-[#6e172c] px-4 py-3 font-semibold text-white hover:bg-[#561324]">Submit section</button></div></form>
      </section><p className="mx-auto mt-5 max-w-2xl text-center text-xs leading-5 text-slate-500">Your information is private to this Family Care Case. Do not forward this access link.</p></div>
  </main>;
}
