import Link from 'next/link';
import {AppShell} from '@/components/app-shell';
import {ActionForm} from '@/components/action-form';
import {createClient} from '@/lib/supabase/server';
import {saveDeliverySettings} from './actions';
import {dateLabel,label} from '@/lib/pipeline';
export default async function NotificationSettings(){
 const client=await createClient();
 const [settings,deliveries]=await Promise.all([client.from('delivery_settings').select('email_enabled').maybeSingle(),client.from('email_deliveries').select('id,case_id,subject,status,attempts,last_error,created_at').order('created_at',{ascending:false}).limit(30)]);
 const checks=[['Google app connection',!!process.env.GOOGLE_CLIENT_ID&&!!process.env.GOOGLE_CLIENT_SECRET],['Gmail account authorization',!!process.env.GOOGLE_REFRESH_TOKEN],['Sender email address',!!process.env.GMAIL_FROM],['Background delivery security',!!process.env.CRON_SECRET&&!!process.env.MAIL_DELIVERY_ORGANIZATION_ID]] as const;
 return <AppShell active="settings"><div className="content workflow"><Link className="link" href="/settings">← Settings</Link><header className="commandhero"><div><p className="eyebrow">Family communications</p><h1>Email & Google Voice</h1><p>Control delivery and review updates that need attention.</p></div></header>
 <div className="workflow-grid"><section className="workflow-card"><h2>Automatic Gmail updates</h2><p>{settings.data?.email_enabled?'Enabled for future notifications.':'Paused. No automatic email is being sent.'}</p>{checks.map(([name,ready])=><div className="workflow-row" key={name}><strong>{name}</strong><span className={`badge ${ready?'green':''}`}>{ready?'Configured':'Connection needed'}</span></div>)}<p>Marshall’s Gmail account must authorize this application before it can send email. Connecting Gmail to ChatGPT does not connect this app.</p><ActionForm action={saveDeliverySettings} submit="Save email delivery setting"><label className="check-label"><input name="enabled" type="checkbox" defaultChecked={settings.data?.email_enabled||false}/>Automatically email future family updates</label></ActionForm><p>Only families with email updates enabled on their case are included. Existing drafts are not sent retroactively.</p></section>
 <section className="workflow-card"><h2>Google Voice texts</h2><span className="badge">Staff sends the message</span><p>Your existing Google Voice number stays in use. Case notifications are prepared for copying into Google Voice; record delivery after sending.</p><a className="primary" href="https://voice.google.com/" target="_blank" rel="noreferrer">Open Google Voice</a><p>Google Voice has no documented public automated texting API. Background text delivery would need another provider.</p></section></div>
 <section className="workflow-card"><h2>Email delivery activity</h2>{deliveries.error&&<p className="formerror">Unable to load delivery activity.</p>}{!deliveries.data?.length&&<p>No email deliveries yet.</p>}{deliveries.data?.map(d=><div className="workflow-row" key={d.id}><div><strong>{d.subject}</strong><small>{dateLabel(d.created_at)} · {d.attempts} attempts</small>{d.last_error&&<p>{d.last_error}</p>}</div><span className="badge">{d.status==='accepted'?'Accepted by Gmail':label(d.status)}</span><Link className="link" href={`/cases/${d.case_id}`}>Open case</Link></div>)}<p>“Accepted by Gmail” does not guarantee arrival in the recipient’s inbox. An uncertain result is held for review, not automatically resent.</p></section></div></AppShell>;
}
