import Link from "next/link";
import { AlertCircle, CheckCircle2, FileCheck2, Megaphone } from "lucide-react";
import { AppShell } from "./app-shell";
const metrics = [["Active cases", "12", "4 services this week"], ["Due today", "7", "3 require attention"], ["Family packets", "5", "2 awaiting review"], ["Content drafts", "3", "1 ready to approve"]];
const actions = [{ icon: AlertCircle, title: "Three family updates are due", detail: "Oldest promised update is overdue", tag: "Urgent" }, { icon: FileCheck2, title: "Two packets need staff review", detail: "Submitted by families this morning", tag: "Review" }, { icon: Megaphone, title: "One obituary draft is ready", detail: "Human approval is required before publishing", tag: "Approve" }];
const events = [["CASE.OBITUARY_APPROVED", "Green family obituary", "Content workflow"], ["DEATH_CERTIFICATES.READY", "Williams family · 6 copies", "Family notification"], ["SERVICE.SCHEDULE_CHANGED", "Davis service · Sep 12", "Calendar sync"]];
export function Dashboard() { return <AppShell><div className="content">
  <section className="intro"><div><p className="eyebrow">Tuesday, September 8</p><h1>Good afternoon, Jonte.</h1><p>Here is what deserves attention across Marshall today.</p></div><button className="primary">+ Add new case</button></section>
  <section className="metrics">{metrics.map((m, i) => <article className="card metric" key={m[0]}><span>{m[0]}</span><strong>{m[1]}</strong><small className={i === 1 ? "alert" : ""}>{m[2]}</small></article>)}</section>
  <div className="grid"><section className="panel"><div className="panelhead"><div><p className="eyebrow">Action center</p><h2>Needs attention</h2></div><Link className="link" href="/tasks">View all tasks</Link></div><div className="attention">{actions.map(({ icon: Icon, ...item }) => <article key={item.title}><span className="iconbox"><Icon size={18} /></span><div><h3>{item.title}</h3><p>{item.detail}</p></div><span className="badge">{item.tag}</span></article>)}</div></section>
  <aside className="panel briefing"><p className="eyebrow">Daily briefing</p><h2>Three things to know</h2><ul><li><b>Saturday staffing:</b> one service still needs a second attendant.</li><li><b>Family care:</b> death certificates are ready for the Williams family.</li><li><b>Content:</b> the Green obituary is approved and queued for review.</li></ul></aside></div>
  <section className="panel events"><div className="panelhead"><div><p className="eyebrow">Event engine</p><h2>Recent workflow activity</h2></div><span className="badge green"><CheckCircle2 size={12} /> Operational</span></div>{events.map((event, i) => <div className="eventrow" key={event[0]}><b className="eventcode">{event[0]}</b><strong>{event[1]}</strong><span>{event[2]}</span><span className="badge green">{i ? "Done" : "Queued"}</span></div>)}</section>
</div></AppShell>; }
