create extension if not exists pgcrypto;

create type public.case_status as enum ('intake','arrangement','in_service','aftercare','closed');
create type public.task_status as enum ('open','in_progress','blocked','done','cancelled');
create type public.content_status as enum ('draft','in_review','approved','scheduled','published','archived');
create type public.event_status as enum ('pending','processing','delivered','failed','dead_letter');
create type public.communication_channel as enum ('email','sms','whatsapp','phone','in_person','internal');

create table public.organizations (id uuid primary key default gen_random_uuid(), name text not null, slug text not null unique, system_key text not null default 'marshall', settings jsonb not null default '{}', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.users (id uuid primary key references auth.users(id) on delete cascade, organization_id uuid not null references public.organizations(id), full_name text not null, email text, status text not null default 'active', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.roles (id uuid primary key default gen_random_uuid(), organization_id uuid references public.organizations(id), key text not null, name text not null, permissions text[] not null default '{}', unique(organization_id,key));
create table public.user_roles (organization_id uuid not null references public.organizations(id), user_id uuid not null references public.users(id) on delete cascade, role_id uuid not null references public.roles(id) on delete cascade, primary key(user_id,role_id));
create table public.people (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), first_name text not null, middle_name text, last_name text not null, preferred_name text, email text, phone text, notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.families (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), name text not null, primary_contact_id uuid references public.people(id), care_status text not null default 'active', portal_enabled boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.cases (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), family_id uuid references public.families(id), deceased_person_id uuid references public.people(id), case_number text not null, status public.case_status not null default 'intake', director_id uuid references public.users(id), source text, opened_at timestamptz not null default now(), closed_at timestamptz, metadata jsonb not null default '{}', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(organization_id,case_number));
create table public.locations (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), name text not null, kind text not null, address jsonb not null default '{}', contact_person_id uuid references public.people(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.services (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), case_id uuid not null references public.cases(id) on delete cascade, location_id uuid references public.locations(id), kind text not null, title text, starts_at timestamptz, ends_at timestamptz, status text not null default 'planning', calendar_event_id text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.tasks (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), case_id uuid references public.cases(id) on delete cascade, service_id uuid references public.services(id) on delete cascade, title text not null, description text, status public.task_status not null default 'open', priority smallint not null default 2 check(priority between 1 and 4), assigned_to uuid references public.users(id), due_at timestamptz, completed_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.documents (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), case_id uuid references public.cases(id) on delete cascade, family_id uuid references public.families(id) on delete cascade, kind text not null, title text not null, status text not null default 'draft', storage_path text, version integer not null default 1, approved_by uuid references public.users(id), approved_at timestamptz, metadata jsonb not null default '{}', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.communications (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), case_id uuid references public.cases(id), family_id uuid references public.families(id), person_id uuid references public.people(id), channel public.communication_channel not null, direction text not null check(direction in ('inbound','outbound','internal')), subject text, body text, external_id text, sent_at timestamptz, created_by uuid references public.users(id), created_at timestamptz not null default now());
create table public.payments (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), case_id uuid references public.cases(id), amount_cents bigint not null check(amount_cents>=0), currency text not null default 'USD', status text not null default 'pending', method text, external_id text, received_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.relationships (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), from_person_id uuid references public.people(id), to_person_id uuid references public.people(id), family_id uuid references public.families(id), relationship_type text not null, is_legal_next_of_kin boolean not null default false, metadata jsonb not null default '{}', created_at timestamptz not null default now());
create table public.content (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), case_id uuid references public.cases(id), document_id uuid references public.documents(id), title text not null, channel text not null, body text, status public.content_status not null default 'draft', current_version integer not null default 1, approved_by uuid references public.users(id), approved_at timestamptz, buffer_update_id text, scheduled_for timestamptz, published_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), check(status not in ('approved','scheduled','published') or (approved_by is not null and approved_at is not null)));
create table public.events (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), name text not null check(name ~ '^[A-Z][A-Z0-9_]*(\.[A-Z][A-Z0-9_]*)+$'), aggregate_type text not null, aggregate_id uuid not null, actor_id uuid references public.users(id), payload jsonb not null default '{}', idempotency_key text not null, status public.event_status not null default 'pending', attempts integer not null default 0, occurred_at timestamptz not null default now(), available_at timestamptz not null default now(), delivered_at timestamptz, last_error text, unique(organization_id,idempotency_key));
create table public.activity_log (id bigint generated always as identity primary key, organization_id uuid not null references public.organizations(id), actor_id uuid references public.users(id), action text not null, entity_type text not null, entity_id uuid, changes jsonb not null default '{}', created_at timestamptz not null default now());
create table public.knowledge (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), title text not null, kind text not null default 'procedure', body text not null, status text not null default 'draft', owner_id uuid references public.users(id), tags text[] not null default '{}', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.integrations (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), provider text not null, status text not null default 'disconnected', config jsonb not null default '{}', secret_reference text, last_synced_at timestamptz, unique(organization_id,provider));
create table public.workflow_rules (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), name text not null, event_name text not null, destination text not null, enabled boolean not null default true, config jsonb not null default '{}', created_at timestamptz not null default now(), updated_at timestamptz not null default now());

create index events_pending_idx on public.events(status,available_at) where status in ('pending','failed');
create index cases_org_status_idx on public.cases(organization_id,status);
create index tasks_org_due_idx on public.tasks(organization_id,due_at) where status not in ('done','cancelled');
create index services_org_start_idx on public.services(organization_id,starts_at);

create function public.current_organization_id() returns uuid language sql stable set search_path='' as $$ select nullif((select auth.jwt()->'app_metadata'->>'organization_id'),'')::uuid $$;

do $$ declare t text; begin foreach t in array array['organizations','users','roles','user_roles','people','families','cases','locations','services','tasks','documents','communications','payments','relationships','content','events','activity_log','knowledge','integrations','workflow_rules'] loop execute format('alter table public.%I enable row level security',t); execute format('revoke all on table public.%I from anon, authenticated',t); execute format('grant select, insert, update, delete on table public.%I to authenticated',t); if t='organizations' then execute 'create policy organization_isolation on public.organizations for select to authenticated using (id=(select public.current_organization_id()))'; else execute format('create policy %I on public.%I for select to authenticated using (organization_id=(select public.current_organization_id()))',t||'_select',t); execute format('create policy %I on public.%I for insert to authenticated with check (organization_id=(select public.current_organization_id()))',t||'_insert',t); execute format('create policy %I on public.%I for update to authenticated using (organization_id=(select public.current_organization_id())) with check (organization_id=(select public.current_organization_id()))',t||'_update',t); execute format('create policy %I on public.%I for delete to authenticated using (organization_id=(select public.current_organization_id()))',t||'_delete',t); end if; end loop; end $$;

revoke insert,update,delete on public.events,public.activity_log from authenticated;

create schema if not exists private;
revoke all on schema private from public, anon, authenticated;
create function private.emit_document_event() returns trigger language plpgsql security definer set search_path='' as $$ declare event_name text; begin if (select auth.uid()) is null or new.organization_id is distinct from (select public.current_organization_id()) then raise exception 'Unauthorized event emission'; end if; if new.kind='obituary' and new.status='approved' and old.status is distinct from new.status then event_name:='CASE.OBITUARY_APPROVED'; elsif new.kind='death_certificate' and new.status='ready' and old.status is distinct from new.status then event_name:='DEATH_CERTIFICATES.READY'; else return new; end if; insert into public.events(organization_id,name,aggregate_type,aggregate_id,actor_id,payload,idempotency_key) values(new.organization_id,event_name,'document',new.id,(select auth.uid()),jsonb_build_object('document_id',new.id,'case_id',new.case_id,'family_id',new.family_id,'version',new.version),event_name||':'||new.id||':v'||new.version) on conflict do nothing; return new; end $$;
revoke all on function private.emit_document_event() from public, anon, authenticated;
create trigger documents_emit_events after update on public.documents for each row execute function private.emit_document_event();

comment on table public.events is 'Transactional outbox consumed by n8n; consumers must use idempotency_key.';
comment on table public.integrations is 'Stores provider state and secret references only; credentials live in Vercel/n8n secret stores.';
