import Link from 'next/link';
import { portalAccess } from '@/lib/portal';
import { fields,labels,type SectionKey } from '@/lib/packet-fields';
import { ActionForm } from '@/components/action-form';
import { familyAction } from '@/app/pipeline-actions';
import { dateLabel,label,type DocumentRecord,type TaskRecord } from '@/lib/pipeline';
export const dynamic='force-dynamic';
export const metadata={title:'Your Family Care | Marshall',robots:{index:false,follow:false},referrer:'no-referrer' as const};
export default async function FamilyPage({params,searchParams}:{params:Promise<{token:string}>;searchParams:Promise<{section?:string}>}) {
 const {token}=await params;const query=await searchParams;
 let access;try{access=await portalAccess(token);}catch{return <main className="family-portal"><section className="workflow-card"><p className="eyebrow">Marshall Family Care</p><h1>This private link is unavailable.</h1><p>It may have expired or been revoked. Please contact Marshall Funeral Home for a new link.</p></section></main>;}
 const {client,link}=access;
 const [c,d,t,s]=await Promise.all([
 client.from('cases').select('case_number,metadata').eq('id',link.case_id).single(),
 client.from('documents').select('id,case_id,title,kind,status,storage_path,metadata,updated_at').eq('case_id',link.case_id).eq('metadata->>family_visible','true').order('created_at').limit(100),
 client.from('tasks').select('id,case_id,title,status,family_visible,due_at').eq('case_id',link.case_id).eq('family_visible',true).order('created_at').limit(100),
 client.from('services').select('title,starts_at,status').eq('case_id',link.case_id).eq('kind','arrangement')]);
 if([c,d,t,s].some(r=>r.error))throw new Error('We could not load your family packet. Please try again.');
 const docs=(d.data||[]) as DocumentRecord[],tasks=(t.data||[])as TaskRecord[];
 const section=Object.hasOwn(fields,query.section||'')?query.section as SectionKey:'general';
 const worksheet=docs.find(d=>d.metadata.section===section);
 return <main className="family-portal workflow"><header className="family-hero"><span className="brandmark">M</span><p className="eyebrow">Marshall Funeral Home</p><h1>Your family care plan</h1><p>{String(c.data?.metadata.decedent_name||c.data?.case_number||'Your family')} · Private family portal</p></header>
 <div className="workflow-grid"><section className="workflow-card"><h2>Your arrangement appointment</h2>{s.data?.length?s.data.map((a,i)=><p key={i}><strong>{dateLabel(a.starts_at)}</strong><br/>{a.title} · {a.status}</p>):<p>Marshall staff will confirm your arrangement appointment here.</p>}</section><section className="workflow-card"><h2>Death certificates</h2><p>{docs.find(d=>d.kind==='death_certificate')?`Current status: ${label(docs.find(d=>d.kind==='death_certificate')!.status)}`:'We will keep you updated here as your certificates progress.'}</p></section></div>
 <section className="workflow-card"><h2>Your family checklist</h2>{!tasks.length&&<p>Your care team will add any items needed here.</p>}{tasks.map(task=><div className="workflow-row" key={task.id}><strong>{task.title}</strong>{task.status==='done'?<span className="badge green">Complete</span>:<ActionForm action={familyAction} submit="Mark complete"><input type="hidden" name="token" value={token}/><input type="hidden" name="op" value="task"/><input type="hidden" name="record_id" value={task.id}/></ActionForm>}</div>)}</section>
 <section className="workflow-card"><h2>Your family packet</h2><p>Save your progress, return with this private link, and submit each section for staff review.</p><nav className="workflow-tabs">{Object.entries(labels).map(([key,title])=><Link key={key} href={`/family/${token}?section=${key}`} aria-current={section===key?'page':undefined}>{title}<small>{label(docs.find(d=>d.metadata.section===key)?.status||'incomplete')}</small></Link>)}</nav>
 <h2>{labels[section]}</h2>{section==='embalming'&&<p>Provide your preference and representative details for staff review. Marshall staff will arrange any required signature separately.</p>}
 {worksheet?.status==='approved'?<p className="workflow-success">Staff have approved this section. Contact your care team if you need a correction.</p>:<ActionForm key={section} action={familyAction} submit="Save section"><input type="hidden" name="token" value={token}/><input type="hidden" name="op" value="section"/><input type="hidden" name="section" value={section}/>{fields[section].map(group=><div className="packet-group" key={group.title}><h3>{group.title}</h3>{group.fields.filter(f=>!['photo','signatureIntent','attestation'].includes(f.name)).map(field=><label key={field.name}>{field.label}{field.required?' *':''}{field.type==='select'?<select name={field.name} defaultValue={worksheet?.metadata.responses?.[field.name]||''}><option value="">Select</option>{field.options?.map(o=><option key={o}>{o}</option>)}</select>:field.type==='textarea'?<textarea name={field.name} rows={4} defaultValue={worksheet?.metadata.responses?.[field.name]||''}/>:<input name={field.name} type={field.type||'text'} defaultValue={worksheet?.metadata.responses?.[field.name]||''}/>}</label>)}</div>)}<label>Save or submit<select name="intent"><option value="save">Save draft and return later</option><option value="submit">Submit for staff review</option></select></label></ActionForm>}
 </section><section className="workflow-card"><h2>Documents to send & receive</h2><p>Upload PDFs or images up to 5 MB. Please provide Social Security numbers directly to your care team, not through these worksheets.</p>{docs.filter(d=>!d.metadata.section&&d.kind!=='death_certificate').map(doc=><div className="workflow-row" key={doc.id}><div><strong>{doc.title}</strong><small>{label(doc.status)}</small></div>{doc.storage_path&&<a className="link" href={`/family/${token}/documents/${doc.id}`}>Download</a>}{doc.status==='requested'&&<ActionForm action={familyAction} submit="Send document"><input type="hidden" name="op" value="upload"/><input type="hidden" name="token" value={token}/><input type="hidden" name="record_id" value={doc.id}/><label>Choose file<input type="file" name="file" required accept="application/pdf,image/jpeg,image/png,image/webp"/></label></ActionForm>}</div>)}<ActionForm action={familyAction} submit="Send file to Marshall"><input type="hidden" name="token" value={token}/><input type="hidden" name="op" value="upload"/><label>File description<input name="title" required placeholder="Obituary photograph"/></label><label>Choose file<input type="file" name="file" required accept="application/pdf,image/jpeg,image/png,image/webp"/></label></ActionForm></section>
 <p className="family-footer">Your private link gives access to this family’s information. Please do not forward it.</p></main>;
}
