import Link from 'next/link';
import { portalAccess } from '@/lib/portal';
import { fields,labels,type SectionKey } from '@/lib/packet-fields';
import { ActionForm } from '@/components/action-form';
import { VoiceField } from '@/components/voice-field';
import { familyAction } from '@/app/pipeline-actions';
import { label,type DocumentRecord } from '@/lib/pipeline';
export const dynamic='force-dynamic';
export const metadata={title:'Your Family Care | Marshall',robots:{index:false,follow:false},referrer:'no-referrer' as const};
export default async function FamilyPage({params,searchParams}:{params:Promise<{token:string}>;searchParams:Promise<{section?:string}>}) {
 const {token}=await params;const query=await searchParams;
 let access;try{access=await portalAccess(token);}catch{return <main className="family-portal"><section className="workflow-card"><p className="eyebrow">Marshall Family Care</p><h1>This private link is unavailable.</h1><p>It may have expired or been revoked. Please contact Marshall Funeral Home for a new link.</p></section></main>;}
 const {client,link}=access;
 const [c,d]=await Promise.all([
 client.from('cases').select('case_number,metadata').eq('id',link.case_id).single(),
 client.from('documents').select('id,case_id,title,kind,status,storage_path,metadata,updated_at').eq('case_id',link.case_id).eq('metadata->>family_visible','true').order('created_at').limit(100)]);
 if([c,d].some(r=>r.error))throw new Error('We could not load your family packet. Please try again.');
 const docs=(d.data||[]) as DocumentRecord[];
 const section=Object.hasOwn(fields,query.section||'')?query.section as SectionKey:'general';
 const worksheet=docs.find(d=>d.metadata.section===section);
 return <main className="family-portal workflow"><header className="family-hero"><span className="brandmark">M</span><p className="eyebrow">Marshall Funeral Home</p><h1>Your family care plan</h1><p>{String(c.data?.metadata.decedent_name||c.data?.case_number||'Your family')} · Private family portal</p></header>
 <section className="workflow-card family-packet-card"><div className="packet-intro"><p className="eyebrow">Private family packet</p><h2>Your family packet</h2><p>Please fill out each section to the best of your ability. You can save your progress and return anytime using this private link.</p></div><div className="packet-accordion" aria-label="Family packet sections">{Object.entries(labels).map(([key,title],index)=>{const active=section===key;const status=label(docs.find(d=>d.metadata.section===key)?.status||'incomplete');return <article className={`packet-accordion-item${active?' is-open':''}`} key={key}><Link className="packet-tab" href={`/family/${token}?section=${key}`} aria-current={active?'page':undefined} aria-expanded={active} aria-controls={`packet-panel-${key}`}><span className="packet-tab-number">{index+1}</span><span className="packet-tab-copy"><strong>{title}</strong><small>{status}</small></span><span className="packet-tab-arrow" aria-hidden="true">{active?'−':'+'}</span></Link>{active&&<div className="packet-panel" id={`packet-panel-${key}`}><h2>{labels[section]}</h2>{section==='embalming'&&<p>Provide your preference and representative details for staff review. Marshall staff will arrange any required signature separately.</p>}{worksheet?.status==='approved'?<p className="workflow-success">Staff have approved this section. Contact your care team if you need a correction.</p>:<ActionForm key={section} action={familyAction} submit="Save section"><input type="hidden" name="token" value={token}/><input type="hidden" name="op" value="section"/><input type="hidden" name="section" value={section}/><p className="voice-form-help"><MicIcon/> Tap <strong>Speak</strong> beside a field to say your answer, then review it before saving.</p>{fields[section].map(group=><div className="packet-group" key={group.title}><h3>{group.title}</h3>{group.fields.filter(f=>!['photo','signatureIntent','attestation'].includes(f.name)).map(field=><VoiceField key={field.name} name={field.name} label={field.label} type={field.type} options={field.options} required={field.required} defaultValue={String(worksheet?.metadata.responses?.[field.name]||'')}/>)}</div>)}<label>Save or submit<select name="intent"><option value="save">Save draft and return later</option><option value="submit">Submit for staff review</option></select></label></ActionForm>}</div>}</article>})}</div>
 </section><section className="workflow-card"><h2>Documents to send & receive</h2><p>Upload PDFs or images up to 5 MB. Please provide Social Security numbers directly to your care team, not through these worksheets.</p>{docs.filter(d=>!d.metadata.section&&d.kind!=='death_certificate').map(doc=><div className="workflow-row" key={doc.id}><div><strong>{doc.title}</strong><small>{label(doc.status)}</small></div>{doc.storage_path&&<a className="link" href={`/family/${token}/documents/${doc.id}`}>Download</a>}{doc.status==='requested'&&<ActionForm action={familyAction} submit="Send document"><input type="hidden" name="op" value="upload"/><input type="hidden" name="token" value={token}/><input type="hidden" name="record_id" value={doc.id}/><label>Choose file<input type="file" name="file" required accept="application/pdf,image/jpeg,image/png,image/webp"/></label></ActionForm>}</div>)}<ActionForm action={familyAction} submit="Send file to Marshall"><input type="hidden" name="token" value={token}/><input type="hidden" name="op" value="upload"/><label>File description<input name="title" required placeholder="Obituary photograph"/></label><label>Choose file<input type="file" name="file" required accept="application/pdf,image/jpeg,image/png,image/webp"/></label></ActionForm></section>
 <p className="family-footer">Your private link gives access to this family’s information. Please do not forward it.</p></main>;
}

function MicIcon(){return <span aria-hidden="true">🎙️</span>}
